"""Curated clue bank: one clue per answer word used across the seeded issues.
Keep clues distinct and family-friendly. Add entries here when new grids
introduce new words; build_issues.py asserts every answer has a clue."""

CLUES = {
    # --- 3-letter fill ---
    "ACE": "Tennis serve nobody returns",
    "ADD": "Sum up",
    "AGE": "Years you've lived",
    "AGO": "In the past",
    "AIR": "What you breathe",
    "ALE": "Pub brew",
    "AND": "Ampersand's meaning",
    "ANT": "Picnic pest",
    "APE": "Gorilla, for one",
    "APT": "Fitting",
    "ARC": "Curved path",
    "ARE": "\"You ___ here\"",
    "ASH": "Fireplace leftovers",
    "BAD": "Not good",
    "BAG": "Grocery carrier",
    "BAN": "Official prohibition",
    "BED": "Place to sleep",
    "BEE": "Honey maker",
    "BEG": "Plead",
    "BET": "Wager",
    "BIG": "Large",
    "BIT": "Small amount",
    "BOA": "Constricting snake",
    "BOW": "Archer's weapon",
    "BUD": "Flower before it opens",
    "BUS": "Public transit ride",
    "CAN": "Aluminum container",
    "COD": "Fish in fish sticks",
    "COO": "Pigeon's sound",
    "COY": "Playfully shy",
    "DAM": "Beaver's build",
    "DAY": "Twenty-four hours",
    "DOT": "Period, essentially",
    "EAR": "Corn unit, or hearing organ",
    "EAT": "Have a meal",
    "EEL": "Slippery swimmer",
    "EGG": "Breakfast staple",
    "EGO": "Sense of self",
    "ELK": "Large antlered deer",
    "ELM": "Street of horror films",
    "END": "Finish",
    "EON": "Very long time",
    "ERA": "Historical period",
    "EWE": "Female sheep",
    "EYE": "Needle's hole, or what you see with",
    "GEL": "Hair-styling goo",
    "GEM": "Precious stone",
    "GOO": "Sticky stuff",
    "ICE": "Frozen water",
    "ILK": "Type or kind",
    "ILL": "Under the weather",
    "INN": "Roadside lodging",
    "ION": "Electrically charged particle",
    "IRE": "Anger",
    "KEY": "It opens a lock",
    "LED": "Guided",
    "LEG": "Table's support",
    "LET": "Allow",
    "LID": "Jar topper",
    "LIE": "Fib",
    "LIT": "Illuminated",
    "LOB": "High, arcing throw",
    "LOW": "Not high",
    "MOD": "Trendy, in '60s London",
    "MOP": "Floor-cleaning tool",
    "NAG": "Pester",
    "NET": "Goal's mesh",
    "NEW": "Fresh out of the box",
    "NIL": "Nothing, in soccer",
    "NIP": "Small bite",
    "NOD": "Silent yes",
    "NOR": "Neither's partner",
    "NOW": "At this moment",
    "NUN": "Convent dweller",
    "OAR": "Rowboat paddle",
    "OAT": "Porridge grain",
    "OIL": "Slippery engine fluid",
    "ONE": "The loneliest number",
    "ORE": "Rock you mine metal from",
    "OWE": "Be in debt",
    "OWL": "Nocturnal hooter",
    "OWN": "Possess",
    "PEG": "Coat hook",
    "PER": "For each",
    "PIG": "Farm oinker",
    "PRY": "Snoop",
    "RED": "Stop-light color",
    "RIP": "Tear",
    "ROB": "Hold up",
    "ROE": "Fish eggs",
    "ROT": "Decay",
    "RUB": "Massage",
    "RUE": "Regret",
    "SEA": "Body of salt water",
    "SET": "Tennis match segment",
    "SIN": "Moral wrong",
    "SIR": "Knight's title",
    "SOD": "Piece of turf",
    "SON": "Male child",
    "SPA": "Place for a soak",
    "SPY": "Secret agent",
    "STY": "Pig's pen",
    "TAG": "Playground game of chase",
    "TAN": "Sun-kissed color",
    "TAR": "Road-paving goo",
    "TEA": "Steeped drink",
    "TEE": "Golf ball's perch",
    "TEN": "Fingers on two hands",
    "TIE": "Necktie, or a draw",
    "TIN": "Cookie container metal",
    "TOE": "Foot digit",
    "TOY": "Plaything",
    "TRY": "Attempt",
    "TWO": "A pair",
    "URN": "Coffee dispenser",
    "USE": "Put to work",
    "VET": "Animal doctor",
    "VIE": "Compete",
    "WEE": "Tiny",
    "WET": "Not dry",
    "WIN": "Be victorious",
    "WOW": "Impress greatly",
    "YET": "So far",
    "YEW": "Evergreen with red berries",

    # --- 7-letter marquee answers ---
    "ABILITY": "Skill or talent",
    "ACCOUNT": "Bank record",
    "ACTRESS": "Woman with a film role",
    "ANCIENT": "Very, very old",
    "ANTENNA": "TV signal catcher",
    "ATTRACT": "Draw in",
    "DEALING": "Handing out the cards",
    "DECIDED": "Made up one's mind",
    "DECLINE": "Politely say no",
    "DESPITE": "In spite of",
    "DEVOTED": "Loyally dedicated",
    "DRESSED": "Put on clothes",
    "ELDERLY": "On in years",
    "ENABLED": "Made possible",
    "ENDLESS": "Going on forever",
    "ETERNAL": "Lasting for all time",
    "EVIDENT": "Plain to see",
    "GENERAL": "Army's top commander",
    "GETTING": "Obtaining",
    "INITIAL": "First, or a monogram letter",
    "LARGEST": "Biggest of all",
    "MARTIAL": "___ arts",
    "NEUTRAL": "Taking no side",
    "NOVELTY": "A new and unusual thing",
    "OPINION": "Point of view",
    "PORTION": "Serving size",
    "RAILWAY": "Train's network of tracks",
    "RENEWAL": "Subscription extension",
    "RETREAT": "Withdraw, or a quiet getaway",
    "SHUTTLE": "Space craft, or an airport bus",
    "SOLDIER": "Member of an army",
    "STUDIED": "Hit the books",
    "TENSION": "Nervous strain",
    "TRINITY": "A group of three",
    "TWISTED": "Wrung, or warped",
    "UTILITY": "Gas or electric service",
    "VOLTAGE": "Electrical force, in volts",
    "WEDDING": "Marriage ceremony",
    "WEEKEND": "Saturday and Sunday",
    "WINNING": "Finishing in first place",

    # --- added for the varied-grid issues ---
    "ADDED": "Included as an extra",
    "ADONIS": "Strikingly handsome man",
    "ALARMED": "Suddenly frightened",
    "ALIAS": "Assumed name",
    "ALL": "Every bit of it",
    "APPROVE": "Give the green light to",
    "ARM": "Shoulder-to-hand limb",
    "ART": "What a gallery displays",
    "ARTIST": "Painter or sculptor",
    "ATOP": "Resting on the top of",
    "ATTIRE": "Clothing",
    "AVOCADO": "Guacamole fruit",
    "BAR": "Where drinks are served",
    "BARD": "Poet of old",
    "BOY": "Young lad",
    "CAP": "Bottle topper",
    "CIRCUIT": "Closed electrical loop",
    "CORDOBA": "Nicaraguan currency",
    "CRANE": "Long-necked wading bird",
    "CROAK": "Frog's sound",
    "DECREED": "Ordered by law",
    "DEVOTE": "Dedicate, as time",
    "DEW": "Morning moisture on the grass",
    "DIALECT": "Regional way of speaking",
    "DORADO": "Golden game fish",
    "DRAWN": "Sketched",
    "DRY": "Not at all wet",
    "DYE": "Fabric coloring agent",
    "DYED": "Colored, as cloth",
    "EDITED": "Revised for print",
    "EDUCATE": "Teach",
    "ELECTRO": "Prefix with magnet",
    "ELICIT": "Draw out, as a response",
    "ERODE": "Wear away slowly",
    "EYED": "Looked at",
    "FINALE": "Grand closing number",
    "FORTH": "Onward and out",
    "FREAK": "Sudden and odd, as an accident",
    "GARBAGE": "Trash",
    "GET": "Obtain",
    "GLUTTON": "One who overeats",
    "KEEN": "Sharp, or eager",
    "LACED": "Tied up, as shoes",
    "LAVA": "Molten volcanic rock",
    "LINEAGE": "Line of ancestry",
    "LOUDER": "At a higher volume",
    "LOUVRE": "Angled slat in a vent",
    "MANDATE": "Official order",
    "MERGE": "Combine into one",
    "NEUTRON": "Chargeless atomic particle",
    "ORIFICE": "Body opening",
    "ORNATE": "Elaborately decorated",
    "OVATION": "Enthusiastic applause",
    "PACKAGE": "Parcel in the mail",
    "PARABLE": "Story with a moral",
    "PASS": "Go by",
    "PASTA": "Spaghetti or penne",
    "PAY": "Wages",
    "PLANNED": "Arranged in advance",
    "PLOTTED": "Schemed",
    "PORTRAY": "Depict",
    "RAMPAGE": "Wild, destructive spree",
    "RAN": "Sprinted",
    "REBOOT": "Restart, as a computer",
    "RECOUNT": "Tally the votes again",
    "REDO": "Do over",
    "ROAD": "Route for cars",
    "RUN": "Move at a jog",
    "RUPTURE": "Burst open",
    "SALAAM": "Respectful bow of greeting",
    "SCARRED": "Left with a lasting mark",
    "SEATED": "Sitting down",
    "SHIELD": "Knight's protective gear",
    "SLY": "Cunning",
    "SPAR": "Practice-box",
    "SPIDER": "Eight-legged web spinner",
    "STEAMED": "Cooked over boiling water",
    "STUBBED": "Banged, as a toe",
    "STUNNED": "Shocked speechless",
    "SUAVE": "Smoothly charming",
    "TAB": "Restaurant bill",
    "TIDIED": "Straightened up",
    "TOO": "Also",
    "VEERED": "Swerved",
    "WAR": "Armed conflict",
    "WINGMAN": "Loyal sidekick",
    "YEARNED": "Longed",
}
